server:
  servlet:
    context-path: /property-view
  port: 8092

spring:
  datasource:
    url: jdbc:h2:mem:hotel-info-db
    driver-class-name: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
